### ISSUE TITLE
Oversized image in Algorithms Binary Search Tree

### ISSUE THREAD

**Issue by Ethan-Arrowood** [freeCodeCamp/guides#563] opened 2017-09-30 18:59 UTC
<img width="1433" alt="screen shot 2017-09-30 at 2 57 02 pm" src="https://user-images.githubusercontent.com/16144158/31048647-b859772a-a5ef-11e7-8ad5-5ea95cec26d7.png">
Should be an easy css fix. Just set the width of the image element. Would be a good first commit; I'll let someone else take it if they want. If someone needs help I'd be happy to help them if necessary.

**Comment by texas2010** [comment] 2017-09-30 19:05
I think this PR will solve this problem. https://github.com/freeCodeCamp/guides/pull/555

**Comment by systimotic** [comment] 2017-09-30 21:31
Yep, good catch @Ethan-Arrowood! I'll close this as a duplicate of #542, which is about this same issue happening all throughout the Guide.

**Closed by systimotic** 2017-09-30 21:31 UTC
