### ISSUE TITLE
We should have a PR title guideline.

### ISSUE THREAD

**Issue by jamesjpk123** [freeCodeCamp/guides#1853] opened 2017-10-19 23:06 UTC
I was thinking, to avoid potential conflicting PRs on the same subject, that every "content" PR should have the full article title in the name of the PR. If there is a PR that changes an article name, the PR should include both the new and the proposed name. What does everyone else think?

**Comment by texas2010** [comment] 2017-10-19 23:08
yeah, the problem is many people not pay attention and make PR for that. we have this problem since few week ago. so I don't have any idea for solving this problem.

**Comment by texas2010** [comment] 2017-10-19 23:08
opps. i dont meant to close this.

**Comment by davcri** [comment] 2017-10-20 07:37
@jamesjpk123 good idea! I think that in general we should clarify this in the README in order to have cleaner contributions (or some guidelines for reviewers).

We can add something like:
```markdown
# Pull request conventions
Following these conventions you will help reviewers speeding the merging process.

#### Adding an article
If you create a _Variables_ article inside the _Python_ directory,  
the pull request title should be `Python: added "Variables" article`

**Format**: `{Parent category}: added "{Article's title}" article`


#### Updating an article
...

```

What do you think ?

**Comment by jamesjpk123** [comment] 2017-10-20 16:52
That sounds like a really good idea @davcri!

**Comment by davcri** [comment] 2017-10-21 17:56
@Glazy made a good point in #2742. Given the number of PR named `Updated index.md`  we could agree on:
- gently closing (temporary) these PR 
or
- adding the label "change requested" 

In this way reviewers can easily filter these PR. What do you think guys ?

**Comment by HKuz** [comment] 2017-10-29 15:42
Hi everyone, thanks for all the suggestions! I'm going to close this issue since they've been formalized in the new CONTRIBUTING.md file 🎉

**Closed by HKuz** 2017-10-29 15:42 UTC
